
import os
import json
import base64
import sqlite3
import shutil
import random
from datetime import datetime, timedelta

try:
    import win32crypt
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
except ImportError:
    print("Missing dependencies: pywin32 or cryptography")
    exit(1)

def get_chrome_cookies(browser="Chrome"):
    print(f"Extracting cookies for {browser}...")
    local_state_path = os.path.join(os.environ["LOCALAPPDATA"], 
                                    r"Google\Chrome\User Data\Local State")
    cookie_path = os.path.join(os.environ["LOCALAPPDATA"], 
                               r"Google\Chrome\User Data\Default\Network\Cookies")
    
    if browser.lower() == "edge":
        local_state_path = os.path.join(os.environ["LOCALAPPDATA"], 
                                        r"Microsoft\Edge\User Data\Local State")
        cookie_path = os.path.join(os.environ["LOCALAPPDATA"], 
                                   r"Microsoft\Edge\User Data\Default\Network\Cookies")

    if not os.path.exists(local_state_path) or not os.path.exists(cookie_path):
        print("Paths not found.")
        return

    # 1. Get AES Key
    with open(local_state_path, "r", encoding="utf-8") as f:
        state = json.load(f)
    encrypted_key = base64.b64decode(state["os_crypt"]["encrypted_key"])
    encrypted_key = encrypted_key[5:] # Remove DPAPI prefix
    secret_key = win32crypt.CryptUnprotectData(encrypted_key, None, None, None, 0)[1]
    
    # 2. Copy DB (Bypass Lock)
    temp_db = f"cookies_tmp_{random.randint(1000,9999)}.db"
    try:
        shutil.copy2(cookie_path, temp_db)
    except Exception as e:
        print(f"Copy failed (Locked?): {e}")
        # Try reading bytes directly
        try:
            with open(cookie_path, "rb") as f:
                data = f.read()
            with open(temp_db, "wb") as f:
                f.write(data)
        except Exception as e2:
            print(f"Binary read failed: {e2}")
            return

    # 3. Decrypt
    conn = sqlite3.connect(temp_db)
    cursor = conn.cursor()
    cursor.execute("SELECT host_key, name, value, encrypted_value, expires_utc, is_secure FROM cookies")
    
    netscape_content = "# Netscape HTTP Cookie File\n# This file is generated by YouTubeSummarizer\n\n"
    
    count = 0
    for host_key, name, value, encrypted_value, expires_utc, is_secure in cursor.fetchall():
        if not value:
            try:
                nonce = encrypted_value[3:15]
                ciphertext = encrypted_value[15:]
                aesgcm = AESGCM(secret_key)
                value = aesgcm.decrypt(nonce, ciphertext, None).decode("utf-8")
            except Exception:
                continue
        
        # Format: domain, flag, path, secure, expiration, name, value
        secure_str = "TRUE" if is_secure else "FALSE"
        # expires_utc is microseconds (Chrome) or seconds (Edge)? Chrome is microseconds since 1601
        # Netscape needs unix timestamp (seconds)
        # Chrome/Edge timestamp: microseconds since 1601-01-01
        # Unix: seconds since 1970-01-01
        # Diff: 11644473600 seconds
        
        try:
            unix_time = int(expires_utc / 1000000) - 11644473600
        except:
            unix_time = 0
            
        netscape_content += f"{host_key}\tTRUE\t/\t{secure_str}\t{unix_time}\t{name}\t{value}\n"
        count += 1

    conn.close()
    try:
        os.remove(temp_db)
    except:
        pass
        
    out_file = "cookies_netscape.txt"
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(netscape_content)
    
    print(f"Successfully extracted {count} cookies to {out_file}")

if __name__ == "__main__":
    get_chrome_cookies("Chrome")
